import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Playfair_Display, Inter } from 'next/font/google';
import { Toaster } from "sonner";

const editorial = Playfair_Display({ subsets: ['latin'], variable: '--font-editorial' });
const sans = Inter({ subsets: ['latin'], variable: '--font-sans' });

const urbanist = localFont({
  src: "./fonts/Urbanist-VariableFont_wght.ttf",
  variable: "--font-urbanist",
});
const superWarming = localFont({
  src: "./fonts/Super Warming.ttf",
  variable: "--font-super-warming",
});


export const metadata: Metadata = {
  title: "Faith-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${urbanist.variable} ${superWarming.variable} h-full antialiased`}
    >
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
      <body className="min-h-full flex flex-col">
        {children}

        <Toaster position="top-right" richColors closeButton />
      </body>
    </html>
  );
}
